version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-app
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

volumes:
  pgdata:
    external: true # use this for existing volumes
